channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - r-base=3.6.2
  - r-bookdown
  - r-checkpoint
  - r-tidyverse=1.3.0
  - r-here
  - r-knitr
  - r-markdown
  - r-formattable
  - r-plotly
  - r-kableextra
  - r-glue
  - pandoc=2.7.3
  - r-dt
