$schema: "http://json-schema.org/draft-07/schema#"
description: snakemake configuration file
properties:
  seed:
    type: integer
    default: 11
    description: an integer, seed for fastq sample
  samples:
    type: string
    description: path to samples.tsv file
  author:
    type: string
    description: author of the report
  email:
    type: string
    description: author email address
  refgenome:
    type: string
    description: path to sars-cov-2 indexed genome
  refgenome_name:
    type: string
    description: name/description of the sars-cov-2 reference genome sequence

required:
  - samples
  - refgenome
  - refgenome_name
